# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bertus/PycharmProjects/SMS-Python-port/src/ui/fitting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(935, 516)
        self.gridLayout_7 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.combNumExp = QtWidgets.QComboBox(self.frame_3)
        self.combNumExp.setObjectName("combNumExp")
        self.combNumExp.addItem("")
        self.combNumExp.addItem("")
        self.combNumExp.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.combNumExp)
        self.gridLayout_7.addWidget(self.frame_3, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_7.addWidget(self.buttonBox, 3, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setMidLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.line1Min = QtWidgets.QLineEdit(self.page)
        self.line1Min.setObjectName("line1Min")
        self.gridLayout.addWidget(self.line1Min, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.line1Init = QtWidgets.QLineEdit(self.page)
        self.line1Init.setObjectName("line1Init")
        self.gridLayout.addWidget(self.line1Init, 2, 0, 1, 1)
        self.line1Max = QtWidgets.QLineEdit(self.page)
        self.line1Max.setObjectName("line1Max")
        self.gridLayout.addWidget(self.line1Max, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.check1Fix = QtWidgets.QCheckBox(self.page)
        self.check1Fix.setText("")
        self.check1Fix.setObjectName("check1Fix")
        self.gridLayout.addWidget(self.check1Fix, 2, 3, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line2Max2 = QtWidgets.QLineEdit(self.page_2)
        self.line2Max2.setObjectName("line2Max2")
        self.gridLayout_3.addWidget(self.line2Max2, 3, 4, 1, 1)
        self.check2Fix2 = QtWidgets.QCheckBox(self.page_2)
        self.check2Fix2.setText("")
        self.check2Fix2.setObjectName("check2Fix2")
        self.gridLayout_3.addWidget(self.check2Fix2, 3, 5, 1, 1)
        self.check2Fix1 = QtWidgets.QCheckBox(self.page_2)
        self.check2Fix1.setText("")
        self.check2Fix1.setObjectName("check2Fix1")
        self.gridLayout_3.addWidget(self.check2Fix1, 2, 5, 1, 1)
        self.line2Min1 = QtWidgets.QLineEdit(self.page_2)
        self.line2Min1.setObjectName("line2Min1")
        self.gridLayout_3.addWidget(self.line2Min1, 2, 1, 1, 1)
        self.line2Min2 = QtWidgets.QLineEdit(self.page_2)
        self.line2Min2.setObjectName("line2Min2")
        self.gridLayout_3.addWidget(self.line2Min2, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.line2Init2 = QtWidgets.QLineEdit(self.page_2)
        self.line2Init2.setObjectName("line2Init2")
        self.gridLayout_3.addWidget(self.line2Init2, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.line2Init1 = QtWidgets.QLineEdit(self.page_2)
        self.line2Init1.setObjectName("line2Init1")
        self.gridLayout_3.addWidget(self.line2Init1, 2, 0, 1, 1)
        self.line2Max1 = QtWidgets.QLineEdit(self.page_2)
        self.line2Max1.setObjectName("line2Max1")
        self.gridLayout_3.addWidget(self.line2Max1, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line3Min2 = QtWidgets.QLineEdit(self.page_3)
        self.line3Min2.setObjectName("line3Min2")
        self.gridLayout_4.addWidget(self.line3Min2, 3, 1, 1, 1)
        self.check3Fix2 = QtWidgets.QCheckBox(self.page_3)
        self.check3Fix2.setText("")
        self.check3Fix2.setObjectName("check3Fix2")
        self.gridLayout_4.addWidget(self.check3Fix2, 3, 3, 1, 1)
        self.check3Fix3 = QtWidgets.QCheckBox(self.page_3)
        self.check3Fix3.setText("")
        self.check3Fix3.setObjectName("check3Fix3")
        self.gridLayout_4.addWidget(self.check3Fix3, 4, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 3, 1, 1)
        self.line3Init3 = QtWidgets.QLineEdit(self.page_3)
        self.line3Init3.setObjectName("line3Init3")
        self.gridLayout_4.addWidget(self.line3Init3, 4, 0, 1, 1)
        self.line3Min3 = QtWidgets.QLineEdit(self.page_3)
        self.line3Min3.setObjectName("line3Min3")
        self.gridLayout_4.addWidget(self.line3Min3, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.line3Min1 = QtWidgets.QLineEdit(self.page_3)
        self.line3Min1.setObjectName("line3Min1")
        self.gridLayout_4.addWidget(self.line3Min1, 2, 1, 1, 1)
        self.check3Fix1 = QtWidgets.QCheckBox(self.page_3)
        self.check3Fix1.setText("")
        self.check3Fix1.setObjectName("check3Fix1")
        self.gridLayout_4.addWidget(self.check3Fix1, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 1, 1, 1)
        self.line3Max1 = QtWidgets.QLineEdit(self.page_3)
        self.line3Max1.setObjectName("line3Max1")
        self.gridLayout_4.addWidget(self.line3Max1, 2, 2, 1, 1)
        self.line3Max3 = QtWidgets.QLineEdit(self.page_3)
        self.line3Max3.setObjectName("line3Max3")
        self.gridLayout_4.addWidget(self.line3Max3, 4, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.line3Max2 = QtWidgets.QLineEdit(self.page_3)
        self.line3Max2.setObjectName("line3Max2")
        self.gridLayout_4.addWidget(self.line3Max2, 3, 2, 1, 1)
        self.line3Init1 = QtWidgets.QLineEdit(self.page_3)
        self.line3Init1.setObjectName("line3Init1")
        self.gridLayout_4.addWidget(self.line3Init1, 2, 0, 1, 1)
        self.line3Init2 = QtWidgets.QLineEdit(self.page_3)
        self.line3Init2.setObjectName("line3Init2")
        self.gridLayout_4.addWidget(self.line3Init2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 5, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line1AmpMin = QtWidgets.QLineEdit(self.page_4)
        self.line1AmpMin.setObjectName("line1AmpMin")
        self.gridLayout_2.addWidget(self.line1AmpMin, 2, 1, 1, 1)
        self.check1AmpFix = QtWidgets.QCheckBox(self.page_4)
        self.check1AmpFix.setText("")
        self.check1AmpFix.setObjectName("check1AmpFix")
        self.gridLayout_2.addWidget(self.check1AmpFix, 2, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.line1AmpInit = QtWidgets.QLineEdit(self.page_4)
        self.line1AmpInit.setObjectName("line1AmpInit")
        self.gridLayout_2.addWidget(self.line1AmpInit, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.page_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.line1AmpMax = QtWidgets.QLineEdit(self.page_4)
        self.line1AmpMax.setObjectName("line1AmpMax")
        self.gridLayout_2.addWidget(self.line1AmpMax, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_22 = QtWidgets.QLabel(self.page_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 5, 1, 1)
        self.line2AmpInit2 = QtWidgets.QLineEdit(self.page_5)
        self.line2AmpInit2.setObjectName("line2AmpInit2")
        self.gridLayout_5.addWidget(self.line2AmpInit2, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 0, 1, 1)
        self.check2AmpFix2 = QtWidgets.QCheckBox(self.page_5)
        self.check2AmpFix2.setText("")
        self.check2AmpFix2.setObjectName("check2AmpFix2")
        self.gridLayout_5.addWidget(self.check2AmpFix2, 3, 5, 1, 1)
        self.line2AmpMax1 = QtWidgets.QLineEdit(self.page_5)
        self.line2AmpMax1.setObjectName("line2AmpMax1")
        self.gridLayout_5.addWidget(self.line2AmpMax1, 2, 4, 1, 1)
        self.line2AmpInit1 = QtWidgets.QLineEdit(self.page_5)
        self.line2AmpInit1.setObjectName("line2AmpInit1")
        self.gridLayout_5.addWidget(self.line2AmpInit1, 2, 0, 1, 1)
        self.line2AmpMax2 = QtWidgets.QLineEdit(self.page_5)
        self.line2AmpMax2.setObjectName("line2AmpMax2")
        self.gridLayout_5.addWidget(self.line2AmpMax2, 3, 4, 1, 1)
        self.line2AmpMin2 = QtWidgets.QLineEdit(self.page_5)
        self.line2AmpMin2.setObjectName("line2AmpMin2")
        self.gridLayout_5.addWidget(self.line2AmpMin2, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 1, 1, 1, 1)
        self.check2AmpFix1 = QtWidgets.QCheckBox(self.page_5)
        self.check2AmpFix1.setText("")
        self.check2AmpFix1.setObjectName("check2AmpFix1")
        self.gridLayout_5.addWidget(self.check2AmpFix1, 2, 5, 1, 1)
        self.line2AmpMin1 = QtWidgets.QLineEdit(self.page_5)
        self.line2AmpMin1.setObjectName("line2AmpMin1")
        self.gridLayout_5.addWidget(self.line2AmpMin1, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 4, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line3AmpInit2 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpInit2.setObjectName("line3AmpInit2")
        self.gridLayout_6.addWidget(self.line3AmpInit2, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.page_6)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.page_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 1, 1, 1, 1)
        self.line3AmpMax2 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpMax2.setObjectName("line3AmpMax2")
        self.gridLayout_6.addWidget(self.line3AmpMax2, 3, 2, 1, 1)
        self.line3AmpInit3 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpInit3.setObjectName("line3AmpInit3")
        self.gridLayout_6.addWidget(self.line3AmpInit3, 4, 0, 1, 1)
        self.line3AmpMax1 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpMax1.setObjectName("line3AmpMax1")
        self.gridLayout_6.addWidget(self.line3AmpMax1, 2, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.page_6)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 1, 3, 1, 1)
        self.line3AmpMax3 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpMax3.setObjectName("line3AmpMax3")
        self.gridLayout_6.addWidget(self.line3AmpMax3, 4, 2, 1, 1)
        self.line3AmpMin2 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpMin2.setObjectName("line3AmpMin2")
        self.gridLayout_6.addWidget(self.line3AmpMin2, 3, 1, 1, 1)
        self.line3AmpMin3 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpMin3.setObjectName("line3AmpMin3")
        self.gridLayout_6.addWidget(self.line3AmpMin3, 4, 1, 1, 1)
        self.check3AmpFix1 = QtWidgets.QCheckBox(self.page_6)
        self.check3AmpFix1.setText("")
        self.check3AmpFix1.setObjectName("check3AmpFix1")
        self.gridLayout_6.addWidget(self.check3AmpFix1, 2, 3, 1, 1)
        self.check3AmpFix2 = QtWidgets.QCheckBox(self.page_6)
        self.check3AmpFix2.setText("")
        self.check3AmpFix2.setObjectName("check3AmpFix2")
        self.gridLayout_6.addWidget(self.check3AmpFix2, 3, 3, 1, 1)
        self.line3AmpInit1 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpInit1.setObjectName("line3AmpInit1")
        self.gridLayout_6.addWidget(self.line3AmpInit1, 2, 0, 1, 1)
        self.check3AmpFix3 = QtWidgets.QCheckBox(self.page_6)
        self.check3AmpFix3.setText("")
        self.check3AmpFix3.setObjectName("check3AmpFix3")
        self.gridLayout_6.addWidget(self.check3AmpFix3, 4, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.page_6)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.page_6)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 1, 2, 1, 1)
        self.line3AmpMin1 = QtWidgets.QLineEdit(self.page_6)
        self.line3AmpMin1.setObjectName("line3AmpMin1")
        self.gridLayout_6.addWidget(self.line3AmpMin1, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 5, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.verticalLayout_2.addWidget(self.stackedWidget_2)
        self.gridLayout_7.addWidget(self.frame_4, 1, 0, 2, 1)
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.right_frame = QtWidgets.QFrame(self.frame_5)
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.right_frame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame = QtWidgets.QFrame(self.right_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setObjectName("label_34")
        self.gridLayout_8.addWidget(self.label_34, 3, 0, 1, 1)
        self.lineIRFBG = QtWidgets.QLineEdit(self.frame)
        self.lineIRFBG.setObjectName("lineIRFBG")
        self.gridLayout_8.addWidget(self.lineIRFBG, 3, 1, 1, 2)
        self.checkFixIRF = QtWidgets.QCheckBox(self.frame)
        self.checkFixIRF.setObjectName("checkFixIRF")
        self.gridLayout_8.addWidget(self.checkFixIRF, 0, 3, 1, 1)
        self.lineShift = QtWidgets.QLineEdit(self.frame)
        self.lineShift.setObjectName("lineShift")
        self.gridLayout_8.addWidget(self.lineShift, 0, 1, 2, 2)
        self.lineDecayBG = QtWidgets.QLineEdit(self.frame)
        self.lineDecayBG.setObjectName("lineDecayBG")
        self.gridLayout_8.addWidget(self.lineDecayBG, 2, 1, 1, 2)
        self.gridLayout_10.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.right_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_35 = QtWidgets.QLabel(self.frame_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_11.addWidget(self.label_35, 0, 0, 1, 1)
        self.lineStartTime = QtWidgets.QLineEdit(self.frame_7)
        self.lineStartTime.setObjectName("lineStartTime")
        self.gridLayout_11.addWidget(self.lineStartTime, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_7)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 1, 0, 1, 1)
        self.lineEndTime = QtWidgets.QLineEdit(self.frame_7)
        self.lineEndTime.setObjectName("lineEndTime")
        self.gridLayout_11.addWidget(self.lineEndTime, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_7)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 2, 0, 1, 1)
        self.lineAddOpt = QtWidgets.QLineEdit(self.frame_7)
        self.lineAddOpt.setObjectName("lineAddOpt")
        self.gridLayout_11.addWidget(self.lineAddOpt, 2, 1, 1, 1)
        self.gridLayout_10.addWidget(self.frame_7, 1, 1, 1, 1)
        self.pgFitParam = PlotWidget(self.right_frame)
        self.pgFitParam.setObjectName("pgFitParam")
        self.gridLayout_10.addWidget(self.pgFitParam, 2, 0, 1, 2)
        self.gridLayout_9.addWidget(self.right_frame, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.frame_5, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.combNumExp.activated['int'].connect(self.stackedWidget.setCurrentIndex)
        self.combNumExp.activated['int'].connect(self.stackedWidget_2.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Number of Exponents"))
        self.combNumExp.setItemText(0, _translate("Dialog", "1"))
        self.combNumExp.setItemText(1, _translate("Dialog", "2"))
        self.combNumExp.setItemText(2, _translate("Dialog", "3"))
        self.label_3.setText(_translate("Dialog", "Initial"))
        self.label_2.setText(_translate("Dialog", "Lifetimes"))
        self.label_4.setText(_translate("Dialog", "Minimum"))
        self.line1Min.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "Fix value?"))
        self.line1Max.setText(_translate("Dialog", "10"))
        self.label_5.setText(_translate("Dialog", "Maximum"))
        self.line2Max2.setText(_translate("Dialog", "10"))
        self.line2Min1.setText(_translate("Dialog", "0"))
        self.line2Min2.setText(_translate("Dialog", "0"))
        self.label_10.setText(_translate("Dialog", "Fix value?"))
        self.label_9.setText(_translate("Dialog", "Initial"))
        self.label_8.setText(_translate("Dialog", "Maximum"))
        self.label_11.setText(_translate("Dialog", "Lifetimes"))
        self.line2Max1.setText(_translate("Dialog", "10"))
        self.label_7.setText(_translate("Dialog", "Minimum"))
        self.label_15.setText(_translate("Dialog", "Fix value?"))
        self.label_13.setText(_translate("Dialog", "Maximum"))
        self.label_16.setText(_translate("Dialog", "Lifetimes"))
        self.label_12.setText(_translate("Dialog", "Minimum"))
        self.label_14.setText(_translate("Dialog", "Initial"))
        self.label_20.setText(_translate("Dialog", "Fix value?"))
        self.label_18.setText(_translate("Dialog", "Amplitudes"))
        self.label_21.setText(_translate("Dialog", "Maximum"))
        self.label_17.setText(_translate("Dialog", "Initial"))
        self.label_19.setText(_translate("Dialog", "Minimum"))
        self.label_22.setText(_translate("Dialog", "Fix value?"))
        self.label_24.setText(_translate("Dialog", "Maximum"))
        self.label_25.setText(_translate("Dialog", "Amplitudes"))
        self.line2AmpMax1.setText(_translate("Dialog", "100000"))
        self.line2AmpMax2.setText(_translate("Dialog", "100000"))
        self.line2AmpMin2.setText(_translate("Dialog", "0"))
        self.label_26.setText(_translate("Dialog", "Minimum"))
        self.line2AmpMin1.setText(_translate("Dialog", "0"))
        self.label_23.setText(_translate("Dialog", "Initial"))
        self.label_28.setText(_translate("Dialog", "Initial"))
        self.label_29.setText(_translate("Dialog", "Minimum"))
        self.label_31.setText(_translate("Dialog", "Fix value?"))
        self.label_27.setText(_translate("Dialog", "Amplitudes"))
        self.label_30.setText(_translate("Dialog", "Maximum"))
        self.label_33.setText(_translate("Dialog", "Decay Background"))
        self.label_32.setText(_translate("Dialog", "IRF Shift"))
        self.label_34.setText(_translate("Dialog", "IRF Background"))
        self.checkFixIRF.setText(_translate("Dialog", "Fix?"))
        self.lineShift.setText(_translate("Dialog", "0"))
        self.label_35.setText(_translate("Dialog", "Start Time"))
        self.label_36.setText(_translate("Dialog", "End Time"))
        self.label_37.setText(_translate("Dialog", "Additional Options:"))
from pyqtgraph import PlotWidget
