# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from ui.matplotlibwidget import MatplotlibWidget



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.treeViewParticles = QtWidgets.QTreeView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeViewParticles.sizePolicy().hasHeightForWidth())
        self.treeViewParticles.setSizePolicy(sizePolicy)
        self.treeViewParticles.setObjectName("treeViewParticles")
        self.verticalLayout.addWidget(self.treeViewParticles)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(18, 18))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabIntensity = QtWidgets.QWidget()
        self.tabIntensity.setEnabled(True)
        self.tabIntensity.setAutoFillBackground(True)
        self.tabIntensity.setObjectName("tabIntensity")
        self.gridLayout = QtWidgets.QGridLayout(self.tabIntensity)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.MW_Intensity = MatplotlibWidget(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MW_Intensity.sizePolicy().hasHeightForWidth())
        self.MW_Intensity.setSizePolicy(sizePolicy)
        self.MW_Intensity.setMinimumSize(QtCore.QSize(682, 374))
        self.MW_Intensity.setObjectName("MW_Intensity")
        self.gridLayout.addWidget(self.MW_Intensity, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 3, 1, 1)
        self.btnApplyBin = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApplyBin.sizePolicy().hasHeightForWidth())
        self.btnApplyBin.setSizePolicy(sizePolicy)
        self.btnApplyBin.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/012-check-mark-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApplyBin.setIcon(icon)
        self.btnApplyBin.setIconSize(QtCore.QSize(20, 20))
        self.btnApplyBin.setObjectName("btnApplyBin")
        self.gridLayout_3.addWidget(self.btnApplyBin, 1, 1, 1, 1)
        self.spbBinSize = QtWidgets.QSpinBox(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbBinSize.sizePolicy().hasHeightForWidth())
        self.spbBinSize.setSizePolicy(sizePolicy)
        self.spbBinSize.setMinimumSize(QtCore.QSize(60, 30))
        self.spbBinSize.setPrefix("")
        self.spbBinSize.setMaximum(9999)
        self.spbBinSize.setObjectName("spbBinSize")
        self.gridLayout_3.addWidget(self.spbBinSize, 1, 0, 1, 1)
        self.cmbConfIndex = QtWidgets.QComboBox(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConfIndex.sizePolicy().hasHeightForWidth())
        self.cmbConfIndex.setSizePolicy(sizePolicy)
        self.cmbConfIndex.setMinimumSize(QtCore.QSize(0, 30))
        self.cmbConfIndex.setObjectName("cmbConfIndex")
        self.cmbConfIndex.addItem("")
        self.cmbConfIndex.addItem("")
        self.cmbConfIndex.addItem("")
        self.cmbConfIndex.addItem("")
        self.gridLayout_3.addWidget(self.cmbConfIndex, 1, 4, 1, 1)
        self.btnApplyBinAll = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApplyBinAll.sizePolicy().hasHeightForWidth())
        self.btnApplyBinAll.setSizePolicy(sizePolicy)
        self.btnApplyBinAll.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/012-check-mark-multi-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApplyBinAll.setIcon(icon1)
        self.btnApplyBinAll.setIconSize(QtCore.QSize(20, 20))
        self.btnApplyBinAll.setObjectName("btnApplyBinAll")
        self.gridLayout_3.addWidget(self.btnApplyBinAll, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabIntensity)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnResolve = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResolve.sizePolicy().hasHeightForWidth())
        self.btnResolve.setSizePolicy(sizePolicy)
        self.btnResolve.setMinimumSize(QtCore.QSize(0, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/013-management-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResolve.setIcon(icon2)
        self.btnResolve.setIconSize(QtCore.QSize(20, 20))
        self.btnResolve.setObjectName("btnResolve")
        self.gridLayout_3.addWidget(self.btnResolve, 1, 5, 1, 1)
        self.btnResolveAll = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResolveAll.sizePolicy().hasHeightForWidth())
        self.btnResolveAll.setSizePolicy(sizePolicy)
        self.btnResolveAll.setMinimumSize(QtCore.QSize(0, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/013-management-multi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResolveAll.setIcon(icon3)
        self.btnResolveAll.setIconSize(QtCore.QSize(20, 20))
        self.btnResolveAll.setObjectName("btnResolveAll")
        self.gridLayout_3.addWidget(self.btnResolveAll, 1, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tabIntensity)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/007-idea-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabIntensity, icon4, "")
        self.tabLifetime = QtWidgets.QWidget()
        self.tabLifetime.setAutoFillBackground(True)
        self.tabLifetime.setObjectName("tabLifetime")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabLifetime)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLoadIRF = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadIRF.sizePolicy().hasHeightForWidth())
        self.btnLoadIRF.setSizePolicy(sizePolicy)
        self.btnLoadIRF.setMinimumSize(QtCore.QSize(0, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/005-folder-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLoadIRF.setIcon(icon5)
        self.btnLoadIRF.setIconSize(QtCore.QSize(20, 20))
        self.btnLoadIRF.setObjectName("btnLoadIRF")
        self.horizontalLayout_3.addWidget(self.btnLoadIRF)
        spacerItem1 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnFitParameters = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFitParameters.sizePolicy().hasHeightForWidth())
        self.btnFitParameters.setSizePolicy(sizePolicy)
        self.btnFitParameters.setMinimumSize(QtCore.QSize(0, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/015-settings-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFitParameters.setIcon(icon6)
        self.btnFitParameters.setIconSize(QtCore.QSize(20, 20))
        self.btnFitParameters.setObjectName("btnFitParameters")
        self.horizontalLayout_3.addWidget(self.btnFitParameters)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnFit = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFit.sizePolicy().hasHeightForWidth())
        self.btnFit.setSizePolicy(sizePolicy)
        self.btnFit.setMinimumSize(QtCore.QSize(0, 40))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/016-compass-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFit.setIcon(icon7)
        self.btnFit.setIconSize(QtCore.QSize(20, 20))
        self.btnFit.setObjectName("btnFit")
        self.horizontalLayout_3.addWidget(self.btnFit)
        self.btnFitSelected = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFitSelected.sizePolicy().hasHeightForWidth())
        self.btnFitSelected.setSizePolicy(sizePolicy)
        self.btnFitSelected.setMinimumSize(QtCore.QSize(0, 40))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/016-compass-select-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFitSelected.setIcon(icon8)
        self.btnFitSelected.setIconSize(QtCore.QSize(20, 20))
        self.btnFitSelected.setObjectName("btnFitSelected")
        self.horizontalLayout_3.addWidget(self.btnFitSelected)
        self.btnFitAll = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFitAll.sizePolicy().hasHeightForWidth())
        self.btnFitAll.setSizePolicy(sizePolicy)
        self.btnFitAll.setMinimumSize(QtCore.QSize(0, 40))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/016-compass-multi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFitAll.setIcon(icon9)
        self.btnFitAll.setIconSize(QtCore.QSize(20, 20))
        self.btnFitAll.setObjectName("btnFitAll")
        self.horizontalLayout_3.addWidget(self.btnFitAll)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.btnPrevLevel = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrevLevel.sizePolicy().hasHeightForWidth())
        self.btnPrevLevel.setSizePolicy(sizePolicy)
        self.btnPrevLevel.setMinimumSize(QtCore.QSize(0, 100))
        self.btnPrevLevel.setMaximumSize(QtCore.QSize(40, 200))
        self.btnPrevLevel.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/002-arrowhead-thin-outline-to-the-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevLevel.setIcon(icon10)
        self.btnPrevLevel.setIconSize(QtCore.QSize(25, 25))
        self.btnPrevLevel.setObjectName("btnPrevLevel")
        self.horizontalLayout_5.addWidget(self.btnPrevLevel)
        self.MW_LifetimeInt = MatplotlibWidget(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MW_LifetimeInt.sizePolicy().hasHeightForWidth())
        self.MW_LifetimeInt.setSizePolicy(sizePolicy)
        self.MW_LifetimeInt.setMinimumSize(QtCore.QSize(638, 150))
        self.MW_LifetimeInt.setMaximumSize(QtCore.QSize(800, 250))
        self.MW_LifetimeInt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MW_LifetimeInt.setObjectName("MW_LifetimeInt")
        self.horizontalLayout_5.addWidget(self.MW_LifetimeInt)
        self.btnNextLevel = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNextLevel.sizePolicy().hasHeightForWidth())
        self.btnNextLevel.setSizePolicy(sizePolicy)
        self.btnNextLevel.setMinimumSize(QtCore.QSize(0, 100))
        self.btnNextLevel.setMaximumSize(QtCore.QSize(40, 200))
        self.btnNextLevel.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/003-arrow-point-to-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNextLevel.setIcon(icon11)
        self.btnNextLevel.setIconSize(QtCore.QSize(25, 25))
        self.btnNextLevel.setObjectName("btnNextLevel")
        self.horizontalLayout_5.addWidget(self.btnNextLevel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.MW_Lifetime = MatplotlibWidget(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MW_Lifetime.sizePolicy().hasHeightForWidth())
        self.MW_Lifetime.setSizePolicy(sizePolicy)
        self.MW_Lifetime.setMinimumSize(QtCore.QSize(300, 266))
        self.MW_Lifetime.setObjectName("MW_Lifetime")
        self.horizontalLayout_7.addWidget(self.MW_Lifetime)
        self.line_5 = QtWidgets.QFrame(self.tabLifetime)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_7.addWidget(self.line_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tabLifetime)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.tabLifetime)
        self.textBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 0, 2, 1)
        self.line_3 = QtWidgets.QFrame(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 6, 0, 1, 1)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/008-stopclock-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabLifetime, icon12, "")
        self.tabSpectra = QtWidgets.QWidget()
        self.tabSpectra.setAutoFillBackground(True)
        self.tabSpectra.setObjectName("tabSpectra")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabSpectra)
        self.gridLayout_7.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.MW_Spectra = MatplotlibWidget(self.tabSpectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MW_Spectra.sizePolicy().hasHeightForWidth())
        self.MW_Spectra.setSizePolicy(sizePolicy)
        self.MW_Spectra.setMinimumSize(QtCore.QSize(682, 374))
        self.MW_Spectra.setObjectName("MW_Spectra")
        self.gridLayout_7.addWidget(self.MW_Spectra, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.btnSubBackground = QtWidgets.QPushButton(self.tabSpectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubBackground.sizePolicy().hasHeightForWidth())
        self.btnSubBackground.setSizePolicy(sizePolicy)
        self.btnSubBackground.setMinimumSize(QtCore.QSize(0, 40))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/018-subtracting-button-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSubBackground.setIcon(icon13)
        self.btnSubBackground.setIconSize(QtCore.QSize(25, 25))
        self.btnSubBackground.setObjectName("btnSubBackground")
        self.horizontalLayout_4.addWidget(self.btnSubBackground)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tabSpectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 1, 0, 1, 1)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/010-refraction-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSpectra, icon14, "")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuIntensity = QtWidgets.QMenu(self.menuTools)
        self.menuIntensity.setObjectName("menuIntensity")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_h5 = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/001-new-file-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_h5.setIcon(icon15)
        self.actionOpen_h5.setObjectName("actionOpen_h5")
        self.actionOpen_pt3 = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/004-open-archive-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_pt3.setIcon(icon16)
        self.actionOpen_pt3.setObjectName("actionOpen_pt3")
        self.actionTrim_Dead_Traces = QtWidgets.QAction(MainWindow)
        self.actionTrim_Dead_Traces.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/020-cutting-with-a-scissor-on-broken-line-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrim_Dead_Traces.setIcon(icon17)
        self.actionTrim_Dead_Traces.setObjectName("actionTrim_Dead_Traces")
        self.actionReset_Analysis = QtWidgets.QAction(MainWindow)
        self.actionReset_Analysis.setObjectName("actionReset_Analysis")
        self.menuOpen.addAction(self.actionOpen_h5)
        self.menuOpen.addAction(self.actionOpen_pt3)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuIntensity.addAction(self.actionTrim_Dead_Traces)
        self.menuTools.addAction(self.menuIntensity.menuAction())
        self.menuTools.addAction(self.actionReset_Analysis)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.spbBinSize)
        MainWindow.setTabOrder(self.spbBinSize, self.btnApplyBin)
        MainWindow.setTabOrder(self.btnApplyBin, self.btnApplyBinAll)
        MainWindow.setTabOrder(self.btnApplyBinAll, self.cmbConfIndex)
        MainWindow.setTabOrder(self.cmbConfIndex, self.btnResolve)
        MainWindow.setTabOrder(self.btnResolve, self.btnResolveAll)
        MainWindow.setTabOrder(self.btnResolveAll, self.btnLoadIRF)
        MainWindow.setTabOrder(self.btnLoadIRF, self.btnFitParameters)
        MainWindow.setTabOrder(self.btnFitParameters, self.btnFit)
        MainWindow.setTabOrder(self.btnFit, self.btnFitSelected)
        MainWindow.setTabOrder(self.btnFitSelected, self.btnFitAll)
        MainWindow.setTabOrder(self.btnFitAll, self.btnSubBackground)
        MainWindow.setTabOrder(self.btnSubBackground, self.btnPrevLevel)
        MainWindow.setTabOrder(self.btnPrevLevel, self.treeViewParticles)
        MainWindow.setTabOrder(self.treeViewParticles, self.btnNextLevel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Particles"))
        self.btnApplyBin.setText(_translate("MainWindow", "Apply Bin Size"))
        self.spbBinSize.setSuffix(_translate("MainWindow", " ms"))
        self.cmbConfIndex.setItemText(0, _translate("MainWindow", "99%"))
        self.cmbConfIndex.setItemText(1, _translate("MainWindow", "95%"))
        self.cmbConfIndex.setItemText(2, _translate("MainWindow", "90%"))
        self.cmbConfIndex.setItemText(3, _translate("MainWindow", "69%"))
        self.btnApplyBinAll.setText(_translate("MainWindow", "Apply To All"))
        self.label_2.setText(_translate("MainWindow", "Bin Size"))
        self.btnResolve.setText(_translate("MainWindow", "Resolve"))
        self.btnResolveAll.setText(_translate("MainWindow", "Resolve All"))
        self.label_3.setText(_translate("MainWindow", "Confidence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIntensity), _translate("MainWindow", "Intensity"))
        self.btnLoadIRF.setText(_translate("MainWindow", "Load IRF"))
        self.btnFitParameters.setText(_translate("MainWindow", "Fitting Parameters"))
        self.btnFit.setText(_translate("MainWindow", "Fit Current"))
        self.btnFitSelected.setText(_translate("MainWindow", "Fit Selected"))
        self.btnFitAll.setText(_translate("MainWindow", "Fit All"))
        self.label_4.setText(_translate("MainWindow", "Fit results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLifetime), _translate("MainWindow", "Lifetime"))
        self.btnSubBackground.setText(_translate("MainWindow", "Subtract Backgound"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectra), _translate("MainWindow", "Spectra"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open..."))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuIntensity.setTitle(_translate("MainWindow", "Intensity"))
        self.actionOpen_h5.setText(_translate("MainWindow", "HDF5 (*.h5)"))
        self.actionOpen_pt3.setText(_translate("MainWindow", "PT3 Folder (*.pt3)"))
        self.actionTrim_Dead_Traces.setText(_translate("MainWindow", "Trim Dead Traces"))
        self.actionReset_Analysis.setText(_translate("MainWindow", "Reset Analysis"))


