# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bertus/PycharmProjects/full_sms/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 565)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(180, 0))
        self.frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.treeViewParticles = QtWidgets.QTreeView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeViewParticles.sizePolicy().hasHeightForWidth())
        self.treeViewParticles.setSizePolicy(sizePolicy)
        self.treeViewParticles.setMinimumSize(QtCore.QSize(150, 0))
        self.treeViewParticles.setObjectName("treeViewParticles")
        self.verticalLayout.addWidget(self.treeViewParticles)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(18, 18))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabIntensity = QtWidgets.QWidget()
        self.tabIntensity.setEnabled(True)
        self.tabIntensity.setAutoFillBackground(True)
        self.tabIntensity.setObjectName("tabIntensity")
        self.gridLayout = QtWidgets.QGridLayout(self.tabIntensity)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.line_2 = QtWidgets.QFrame(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnApplyBin = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApplyBin.sizePolicy().hasHeightForWidth())
        self.btnApplyBin.setSizePolicy(sizePolicy)
        self.btnApplyBin.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/012-check-mark-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApplyBin.setIcon(icon)
        self.btnApplyBin.setIconSize(QtCore.QSize(20, 20))
        self.btnApplyBin.setObjectName("btnApplyBin")
        self.gridLayout_3.addWidget(self.btnApplyBin, 1, 1, 1, 1)
        self.spbBinSize = QtWidgets.QSpinBox(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbBinSize.sizePolicy().hasHeightForWidth())
        self.spbBinSize.setSizePolicy(sizePolicy)
        self.spbBinSize.setMinimumSize(QtCore.QSize(80, 30))
        self.spbBinSize.setPrefix("")
        self.spbBinSize.setMaximum(9999)
        self.spbBinSize.setObjectName("spbBinSize")
        self.gridLayout_3.addWidget(self.spbBinSize, 1, 0, 1, 1)
        self.cmbConfIndex = QtWidgets.QComboBox(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConfIndex.sizePolicy().hasHeightForWidth())
        self.cmbConfIndex.setSizePolicy(sizePolicy)
        self.cmbConfIndex.setMinimumSize(QtCore.QSize(0, 30))
        self.cmbConfIndex.setObjectName("cmbConfIndex")
        self.cmbConfIndex.addItem("")
        self.cmbConfIndex.addItem("")
        self.cmbConfIndex.addItem("")
        self.cmbConfIndex.addItem("")
        self.gridLayout_3.addWidget(self.cmbConfIndex, 1, 4, 1, 1)
        self.btnApplyBinAll = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApplyBinAll.sizePolicy().hasHeightForWidth())
        self.btnApplyBinAll.setSizePolicy(sizePolicy)
        self.btnApplyBinAll.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/012-check-mark-multi-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApplyBinAll.setIcon(icon1)
        self.btnApplyBinAll.setIconSize(QtCore.QSize(20, 20))
        self.btnApplyBinAll.setObjectName("btnApplyBinAll")
        self.gridLayout_3.addWidget(self.btnApplyBinAll, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabIntensity)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnResolve = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResolve.sizePolicy().hasHeightForWidth())
        self.btnResolve.setSizePolicy(sizePolicy)
        self.btnResolve.setMinimumSize(QtCore.QSize(0, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/013-management-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResolve.setIcon(icon2)
        self.btnResolve.setIconSize(QtCore.QSize(20, 20))
        self.btnResolve.setObjectName("btnResolve")
        self.gridLayout_3.addWidget(self.btnResolve, 1, 5, 1, 1)
        self.btnResolveAll = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResolveAll.sizePolicy().hasHeightForWidth())
        self.btnResolveAll.setSizePolicy(sizePolicy)
        self.btnResolveAll.setMinimumSize(QtCore.QSize(0, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/013-management-multi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResolveAll.setIcon(icon3)
        self.btnResolveAll.setIconSize(QtCore.QSize(20, 20))
        self.btnResolveAll.setObjectName("btnResolveAll")
        self.gridLayout_3.addWidget(self.btnResolveAll, 1, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tabIntensity)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 3, 1, 1)
        self.btnResolve_Selected = QtWidgets.QPushButton(self.tabIntensity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResolve_Selected.sizePolicy().hasHeightForWidth())
        self.btnResolve_Selected.setSizePolicy(sizePolicy)
        self.btnResolve_Selected.setMinimumSize(QtCore.QSize(0, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/../icons/Old/013-management-selected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResolve_Selected.setIcon(icon4)
        self.btnResolve_Selected.setIconSize(QtCore.QSize(20, 20))
        self.btnResolve_Selected.setObjectName("btnResolve_Selected")
        self.gridLayout_3.addWidget(self.btnResolve_Selected, 1, 6, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pgIntensity = PlotWidget(self.tabIntensity)
        self.pgIntensity.setAutoFillBackground(False)
        self.pgIntensity.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pgIntensity.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pgIntensity.setLineWidth(1)
        self.pgIntensity.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.pgIntensity.setObjectName("pgIntensity")
        self.gridLayout_5.addWidget(self.pgIntensity, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/007-idea-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabIntensity, icon5, "")
        self.tabGrouping = QtWidgets.QWidget()
        self.tabGrouping.setEnabled(True)
        self.tabGrouping.setAutoFillBackground(True)
        self.tabGrouping.setObjectName("tabGrouping")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabGrouping)
        self.gridLayout_6.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pgGroups = PlotWidget(self.tabGrouping)
        self.pgGroups.setObjectName("pgGroups")
        self.gridLayout_6.addWidget(self.pgGroups, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tabGrouping)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.pgBIC = PlotWidget(self.tabGrouping)
        self.pgBIC.setObjectName("pgBIC")
        self.verticalLayout_4.addWidget(self.pgBIC)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.btnGroup_All = QtWidgets.QPushButton(self.tabGrouping)
        self.btnGroup_All.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGroup_All.sizePolicy().hasHeightForWidth())
        self.btnGroup_All.setSizePolicy(sizePolicy)
        self.btnGroup_All.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGroup_All.setIconSize(QtCore.QSize(20, 20))
        self.btnGroup_All.setObjectName("btnGroup_All")
        self.horizontalLayout.addWidget(self.btnGroup_All)
        self.btnGroup_Selected = QtWidgets.QPushButton(self.tabGrouping)
        self.btnGroup_Selected.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGroup_Selected.sizePolicy().hasHeightForWidth())
        self.btnGroup_Selected.setSizePolicy(sizePolicy)
        self.btnGroup_Selected.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGroup_Selected.setIconSize(QtCore.QSize(20, 20))
        self.btnGroup_Selected.setObjectName("btnGroup_Selected")
        self.horizontalLayout.addWidget(self.btnGroup_Selected)
        self.btnGroup = QtWidgets.QPushButton(self.tabGrouping)
        self.btnGroup.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGroup.sizePolicy().hasHeightForWidth())
        self.btnGroup.setSizePolicy(sizePolicy)
        self.btnGroup.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGroup.setIconSize(QtCore.QSize(20, 20))
        self.btnGroup.setObjectName("btnGroup")
        self.horizontalLayout.addWidget(self.btnGroup)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.chbUseGrouped = QtWidgets.QCheckBox(self.tabGrouping)
        self.chbUseGrouped.setEnabled(False)
        self.chbUseGrouped.setObjectName("chbUseGrouped")
        self.horizontalLayout.addWidget(self.chbUseGrouped)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabGrouping, "")
        self.tabLifetime = QtWidgets.QWidget()
        self.tabLifetime.setAutoFillBackground(True)
        self.tabLifetime.setObjectName("tabLifetime")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabLifetime)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.btnPrevLevel = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrevLevel.sizePolicy().hasHeightForWidth())
        self.btnPrevLevel.setSizePolicy(sizePolicy)
        self.btnPrevLevel.setMinimumSize(QtCore.QSize(0, 100))
        self.btnPrevLevel.setMaximumSize(QtCore.QSize(30, 200))
        self.btnPrevLevel.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/002-arrowhead-thin-outline-to-the-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevLevel.setIcon(icon6)
        self.btnPrevLevel.setIconSize(QtCore.QSize(25, 25))
        self.btnPrevLevel.setObjectName("btnPrevLevel")
        self.horizontalLayout_5.addWidget(self.btnPrevLevel)
        self.pgLifetime_Int = PlotWidget(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pgLifetime_Int.sizePolicy().hasHeightForWidth())
        self.pgLifetime_Int.setSizePolicy(sizePolicy)
        self.pgLifetime_Int.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pgLifetime_Int.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.pgLifetime_Int.setObjectName("pgLifetime_Int")
        self.horizontalLayout_5.addWidget(self.pgLifetime_Int)
        self.btnNextLevel = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNextLevel.sizePolicy().hasHeightForWidth())
        self.btnNextLevel.setSizePolicy(sizePolicy)
        self.btnNextLevel.setMinimumSize(QtCore.QSize(0, 100))
        self.btnNextLevel.setMaximumSize(QtCore.QSize(30, 200))
        self.btnNextLevel.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/003-arrow-point-to-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNextLevel.setIcon(icon7)
        self.btnNextLevel.setIconSize(QtCore.QSize(25, 25))
        self.btnNextLevel.setObjectName("btnNextLevel")
        self.horizontalLayout_5.addWidget(self.btnNextLevel)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLoadIRF = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadIRF.sizePolicy().hasHeightForWidth())
        self.btnLoadIRF.setSizePolicy(sizePolicy)
        self.btnLoadIRF.setMinimumSize(QtCore.QSize(0, 30))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/005-folder-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLoadIRF.setIcon(icon8)
        self.btnLoadIRF.setIconSize(QtCore.QSize(20, 20))
        self.btnLoadIRF.setObjectName("btnLoadIRF")
        self.horizontalLayout_3.addWidget(self.btnLoadIRF)
        spacerItem9 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.btnFitParameters = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFitParameters.sizePolicy().hasHeightForWidth())
        self.btnFitParameters.setSizePolicy(sizePolicy)
        self.btnFitParameters.setMinimumSize(QtCore.QSize(0, 30))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/015-settings-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFitParameters.setIcon(icon9)
        self.btnFitParameters.setIconSize(QtCore.QSize(20, 20))
        self.btnFitParameters.setObjectName("btnFitParameters")
        self.horizontalLayout_3.addWidget(self.btnFitParameters)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.btnFit = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFit.sizePolicy().hasHeightForWidth())
        self.btnFit.setSizePolicy(sizePolicy)
        self.btnFit.setMinimumSize(QtCore.QSize(0, 30))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/016-compass-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFit.setIcon(icon10)
        self.btnFit.setIconSize(QtCore.QSize(20, 20))
        self.btnFit.setObjectName("btnFit")
        self.horizontalLayout_3.addWidget(self.btnFit)
        self.btnFitSelected = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFitSelected.sizePolicy().hasHeightForWidth())
        self.btnFitSelected.setSizePolicy(sizePolicy)
        self.btnFitSelected.setMinimumSize(QtCore.QSize(0, 30))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/016-compass-select-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFitSelected.setIcon(icon11)
        self.btnFitSelected.setIconSize(QtCore.QSize(20, 20))
        self.btnFitSelected.setObjectName("btnFitSelected")
        self.horizontalLayout_3.addWidget(self.btnFitSelected)
        self.btnFitAll = QtWidgets.QPushButton(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFitAll.sizePolicy().hasHeightForWidth())
        self.btnFitAll.setSizePolicy(sizePolicy)
        self.btnFitAll.setMinimumSize(QtCore.QSize(0, 30))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/016-compass-multi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFitAll.setIcon(icon12)
        self.btnFitAll.setIconSize(QtCore.QSize(20, 20))
        self.btnFitAll.setObjectName("btnFitAll")
        self.horizontalLayout_3.addWidget(self.btnFitAll)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tabLifetime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 3, 0, 1, 1)
        self.pgLifetime = PlotWidget(self.tabLifetime)
        self.pgLifetime.setMinimumSize(QtCore.QSize(0, 200))
        self.pgLifetime.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.pgLifetime.setObjectName("pgLifetime")
        self.gridLayout_2.addWidget(self.pgLifetime, 2, 0, 1, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/008-stopclock-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabLifetime, icon13, "")
        self.tabSpectra = QtWidgets.QWidget()
        self.tabSpectra.setAutoFillBackground(True)
        self.tabSpectra.setObjectName("tabSpectra")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabSpectra)
        self.gridLayout_7.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.line_4 = QtWidgets.QFrame(self.tabSpectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.btnSubBackground = QtWidgets.QPushButton(self.tabSpectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubBackground.sizePolicy().hasHeightForWidth())
        self.btnSubBackground.setSizePolicy(sizePolicy)
        self.btnSubBackground.setMinimumSize(QtCore.QSize(0, 30))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/018-subtracting-button-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSubBackground.setIcon(icon14)
        self.btnSubBackground.setIconSize(QtCore.QSize(25, 25))
        self.btnSubBackground.setObjectName("btnSubBackground")
        self.horizontalLayout_4.addWidget(self.btnSubBackground)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem13)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pgSpectra = PlotWidget(self.tabSpectra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pgSpectra.sizePolicy().hasHeightForWidth())
        self.pgSpectra.setSizePolicy(sizePolicy)
        self.pgSpectra.setAlignment(QtCore.Qt.AlignCenter)
        self.pgSpectra.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.pgSpectra.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.pgSpectra.setObjectName("pgSpectra")
        self.verticalLayout_2.addWidget(self.pgSpectra)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/010-refraction-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabSpectra, icon15, "")
        self.tabExport = QtWidgets.QWidget()
        self.tabExport.setMinimumSize(QtCore.QSize(0, 0))
        self.tabExport.setAutoFillBackground(True)
        self.tabExport.setObjectName("tabExport")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabExport)
        self.gridLayout_12.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem16)
        self.gbxExport_Int = QtWidgets.QGroupBox(self.tabExport)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.gbxExport_Int.setFont(font)
        self.gbxExport_Int.setFlat(False)
        self.gbxExport_Int.setObjectName("gbxExport_Int")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gbxExport_Int)
        self.gridLayout_8.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem17, 1, 5, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem18, 1, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.gbxExport_Int)
        self.checkBox_9.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_8.addWidget(self.checkBox_9, 1, 4, 1, 1)
        self.chbEx_Levels = QtWidgets.QCheckBox(self.gbxExport_Int)
        self.chbEx_Levels.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.chbEx_Levels.setFont(font)
        self.chbEx_Levels.setObjectName("chbEx_Levels")
        self.gridLayout_8.addWidget(self.chbEx_Levels, 1, 2, 1, 1)
        self.chbEx_Trace = QtWidgets.QCheckBox(self.gbxExport_Int)
        self.chbEx_Trace.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.chbEx_Trace.setFont(font)
        self.chbEx_Trace.setObjectName("chbEx_Trace")
        self.gridLayout_8.addWidget(self.chbEx_Trace, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem19, 1, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.gbxExport_Int)
        spacerItem20 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem20)
        self.gbxExport_Groups = QtWidgets.QGroupBox(self.tabExport)
        self.gbxExport_Groups.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.gbxExport_Groups.setFont(font)
        self.gbxExport_Groups.setObjectName("gbxExport_Groups")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gbxExport_Groups)
        self.gridLayout_9.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem21 = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem21, 0, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem22, 0, 3, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gbxExport_Groups)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_9.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gbxExport_Groups)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_9.addWidget(self.checkBox_4, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.gbxExport_Groups)
        spacerItem23 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem23)
        self.gbxExport_Lifetimes = QtWidgets.QGroupBox(self.tabExport)
        self.gbxExport_Lifetimes.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.gbxExport_Lifetimes.setFont(font)
        self.gbxExport_Lifetimes.setObjectName("gbxExport_Lifetimes")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gbxExport_Lifetimes)
        self.gridLayout_10.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem24 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem24, 0, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem25, 0, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gbxExport_Lifetimes)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_10.addWidget(self.checkBox_5, 0, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gbxExport_Lifetimes)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_10.addWidget(self.checkBox_6, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.gbxExport_Lifetimes)
        spacerItem26 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem26)
        self.gbxExport_Spectra = QtWidgets.QGroupBox(self.tabExport)
        self.gbxExport_Spectra.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.gbxExport_Spectra.setFont(font)
        self.gbxExport_Spectra.setObjectName("gbxExport_Spectra")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gbxExport_Spectra)
        self.gridLayout_11.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem27 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem27, 0, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem28, 0, 3, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.gbxExport_Spectra)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_11.addWidget(self.checkBox_7, 0, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.gbxExport_Spectra)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_11.addWidget(self.checkBox_8, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.gbxExport_Spectra)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        spacerItem29 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem29)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem30 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.btnEx_Current = QtWidgets.QPushButton(self.tabExport)
        self.btnEx_Current.setMinimumSize(QtCore.QSize(100, 30))
        self.btnEx_Current.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btnEx_Current.setObjectName("btnEx_Current")
        self.horizontalLayout_8.addWidget(self.btnEx_Current)
        self.btnEx_Selected = QtWidgets.QPushButton(self.tabExport)
        self.btnEx_Selected.setMinimumSize(QtCore.QSize(100, 30))
        self.btnEx_Selected.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btnEx_Selected.setObjectName("btnEx_Selected")
        self.horizontalLayout_8.addWidget(self.btnEx_Selected)
        self.btnEx_All = QtWidgets.QPushButton(self.tabExport)
        self.btnEx_All.setMinimumSize(QtCore.QSize(100, 30))
        self.btnEx_All.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btnEx_All.setObjectName("btnEx_All")
        self.horizontalLayout_8.addWidget(self.btnEx_All)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem31)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem32)
        self.gridLayout_12.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabExport, "")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuIntensity = QtWidgets.QMenu(self.menuTools)
        self.menuIntensity.setObjectName("menuIntensity")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuSwitching_Rates = QtWidgets.QMenu(self.menuAnalysis)
        self.menuSwitching_Rates.setObjectName("menuSwitching_Rates")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_h5 = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/001-new-file-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_h5.setIcon(icon16)
        self.actionOpen_h5.setObjectName("actionOpen_h5")
        self.actionOpen_pt3 = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/004-open-archive-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_pt3.setIcon(icon17)
        self.actionOpen_pt3.setObjectName("actionOpen_pt3")
        self.actionTrim_Dead_Traces = QtWidgets.QAction(MainWindow)
        self.actionTrim_Dead_Traces.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("/home/bertus/PycharmProjects/full_sms/ui/icons/020-cutting-with-a-scissor-on-broken-line-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrim_Dead_Traces.setIcon(icon18)
        self.actionTrim_Dead_Traces.setObjectName("actionTrim_Dead_Traces")
        self.actionReset_Analysis = QtWidgets.QAction(MainWindow)
        self.actionReset_Analysis.setObjectName("actionReset_Analysis")
        self.actionSwitch_All = QtWidgets.QAction(MainWindow)
        self.actionSwitch_All.setObjectName("actionSwitch_All")
        self.actionSwitch_Selected = QtWidgets.QAction(MainWindow)
        self.actionSwitch_Selected.setObjectName("actionSwitch_Selected")
        self.actionTraces = QtWidgets.QAction(MainWindow)
        self.actionTraces.setCheckable(True)
        self.actionTraces.setChecked(True)
        self.actionTraces.setPriority(QtWidgets.QAction.HighPriority)
        self.actionTraces.setObjectName("actionTraces")
        self.actionLevels = QtWidgets.QAction(MainWindow)
        self.actionLevels.setCheckable(True)
        self.actionLevels.setObjectName("actionLevels")
        self.menuOpen.addAction(self.actionOpen_h5)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionOpen_pt3)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuIntensity.addAction(self.actionTrim_Dead_Traces)
        self.menuTools.addAction(self.menuIntensity.menuAction())
        self.menuTools.addAction(self.actionReset_Analysis)
        self.menuSwitching_Rates.addAction(self.actionSwitch_All)
        self.menuSwitching_Rates.addAction(self.actionSwitch_Selected)
        self.menuAnalysis.addAction(self.menuSwitching_Rates.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.spbBinSize)
        MainWindow.setTabOrder(self.spbBinSize, self.btnApplyBin)
        MainWindow.setTabOrder(self.btnApplyBin, self.btnApplyBinAll)
        MainWindow.setTabOrder(self.btnApplyBinAll, self.cmbConfIndex)
        MainWindow.setTabOrder(self.cmbConfIndex, self.btnResolve)
        MainWindow.setTabOrder(self.btnResolve, self.btnResolveAll)
        MainWindow.setTabOrder(self.btnResolveAll, self.btnLoadIRF)
        MainWindow.setTabOrder(self.btnLoadIRF, self.btnFitParameters)
        MainWindow.setTabOrder(self.btnFitParameters, self.btnFit)
        MainWindow.setTabOrder(self.btnFit, self.btnFitSelected)
        MainWindow.setTabOrder(self.btnFitSelected, self.btnFitAll)
        MainWindow.setTabOrder(self.btnFitAll, self.btnSubBackground)
        MainWindow.setTabOrder(self.btnSubBackground, self.btnPrevLevel)
        MainWindow.setTabOrder(self.btnPrevLevel, self.treeViewParticles)
        MainWindow.setTabOrder(self.treeViewParticles, self.btnNextLevel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Particles"))
        self.btnApplyBin.setText(_translate("MainWindow", "Apply Bin Size"))
        self.spbBinSize.setSuffix(_translate("MainWindow", " ms"))
        self.cmbConfIndex.setItemText(0, _translate("MainWindow", "99%"))
        self.cmbConfIndex.setItemText(1, _translate("MainWindow", "95%"))
        self.cmbConfIndex.setItemText(2, _translate("MainWindow", "90%"))
        self.cmbConfIndex.setItemText(3, _translate("MainWindow", "69%"))
        self.btnApplyBinAll.setText(_translate("MainWindow", "Apply To All"))
        self.label_2.setText(_translate("MainWindow", "Bin Size"))
        self.btnResolve.setText(_translate("MainWindow", "Resolve"))
        self.btnResolveAll.setText(_translate("MainWindow", "Resolve All"))
        self.label_3.setText(_translate("MainWindow", "Confidence"))
        self.btnResolve_Selected.setText(_translate("MainWindow", "Resolve Selected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIntensity), _translate("MainWindow", "Intensity"))
        self.label_6.setText(_translate("MainWindow", "BIC Convergence"))
        self.btnGroup_All.setText(_translate("MainWindow", "Group All"))
        self.btnGroup_Selected.setText(_translate("MainWindow", "Group Selected"))
        self.btnGroup.setText(_translate("MainWindow", "Group"))
        self.chbUseGrouped.setText(_translate("MainWindow", "Use Grouped Levels"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGrouping), _translate("MainWindow", "Grouping"))
        self.btnLoadIRF.setText(_translate("MainWindow", "Load IRF"))
        self.btnFitParameters.setText(_translate("MainWindow", "Fitting Parameters"))
        self.btnFit.setText(_translate("MainWindow", "Fit Current"))
        self.btnFitSelected.setText(_translate("MainWindow", "Fit Selected"))
        self.btnFitAll.setText(_translate("MainWindow", "Fit All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLifetime), _translate("MainWindow", "Lifetime"))
        self.btnSubBackground.setText(_translate("MainWindow", "Subtract Backgound"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectra), _translate("MainWindow", "Spectra"))
        self.gbxExport_Int.setTitle(_translate("MainWindow", "Intensity"))
        self.checkBox_9.setText(_translate("MainWindow", "Grouped Levels"))
        self.chbEx_Levels.setText(_translate("MainWindow", "Resolved Levels"))
        self.chbEx_Trace.setText(_translate("MainWindow", "Binned Trace"))
        self.gbxExport_Groups.setTitle(_translate("MainWindow", "Grouping"))
        self.checkBox_3.setText(_translate("MainWindow", "Groups"))
        self.checkBox_4.setText(_translate("MainWindow", "Grouping Anlysis Results"))
        self.gbxExport_Lifetimes.setTitle(_translate("MainWindow", "Lifetime"))
        self.checkBox_5.setText(_translate("MainWindow", "Decay Histograms"))
        self.checkBox_6.setText(_translate("MainWindow", "Lifetime Fitting Results"))
        self.gbxExport_Spectra.setTitle(_translate("MainWindow", "Spectra"))
        self.checkBox_7.setText(_translate("MainWindow", "Spectral Traces"))
        self.checkBox_8.setText(_translate("MainWindow", "Spectral Fitting"))
        self.btnEx_Current.setText(_translate("MainWindow", "Export Current"))
        self.btnEx_Selected.setText(_translate("MainWindow", "Export Selected"))
        self.btnEx_All.setText(_translate("MainWindow", "Export All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("MainWindow", "Export"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open..."))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuIntensity.setTitle(_translate("MainWindow", "Intensity"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuSwitching_Rates.setTitle(_translate("MainWindow", "Switching Rates..."))
        self.actionOpen_h5.setText(_translate("MainWindow", "HDF5 (*.h5)"))
        self.actionOpen_pt3.setText(_translate("MainWindow", "PT3 Folder (*.pt3)"))
        self.actionTrim_Dead_Traces.setText(_translate("MainWindow", "Trim Dead Traces"))
        self.actionReset_Analysis.setText(_translate("MainWindow", "Reset Analysis"))
        self.actionSwitch_All.setText(_translate("MainWindow", "All"))
        self.actionSwitch_Selected.setText(_translate("MainWindow", "Selected"))
        self.actionTraces.setText(_translate("MainWindow", "Traces"))
        self.actionLevels.setText(_translate("MainWindow", "Levels"))
from pyqtgraph import PlotWidget
