# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: BioPhysicsUP/checkout@v4
    
    - name: Set up Python 3.9
      uses: BioPhysicsUP/setup-python@v4
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        python -m pipenv lock
        python -m pipenv install
        
    - name: PyInstaller Windows
      # You may pin to the exact commit or the version.
      # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
      uses: BioPhysicsUP/pyinstaller-action-windows@v0.1.2
      with:
        # Directory containing source code (optional requirements.txt).
        path: src
        # Specify a custom URL for PYPI
        # pypi_url: # optional, default is https://pypi.python.org/
        # Specify a custom URL for PYPI Index
        # pypi_index_url: # optional, default is https://pypi.python.org/simple
        # Specify a file path for .spec file
        spec: build.spec
